name   ="vars"
version="1.0.0"

[dependencies]
  gleam_stdlib=">= 0.34.0 and < 2.0.0"
  envoy       =">= 1.0.2 and < 2.0.0"
  argv        =">= 1.0.2 and < 2.0.0"

[dev-dependencies]
  gleeunit=">= 1.0.0 and < 2.0.0"
gleescript = ">= 1.4.0 and < 2.0.0"
